/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b6c4ff',
        'tertiary-container': '#384055',
        'secondary-container': '#2170e4',
        'on-tertiary-container': '#a4acc5',
        'on-primary-container': '#90a8ff',
        'surface-container-low': '#eff4ff',
        'on-surface': '#0b1c30',
        tertiary: '#222a3e',
        'on-background': '#0b1c30',
        'secondary-fixed': '#d8e2ff',
        'on-error': '#ffffff',
        'inverse-surface': '#213145',
        'outline-variant': '#c5c5d3',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#4059aa',
        'primary-container': '#1e3a8a',
        surface: '#f8f9ff',
        primary: '#00236f',
        secondary: '#0058be',
        'surface-dim': '#cbdbf5',
        outline: '#757682',
        'surface-variant': '#d3e4fe',
        'surface-container': '#e5eeff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-surface-variant': '#444651',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'surface-bright': '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        // Legacy Neo-Shinjuku (student/teacher layouts)
        navy: { 900: '#0e1322', 800: '#161d30', 700: '#1e2841' },
        neon: { blue: '#00D4FF', crimson: '#FF4B6E', cyan: '#00ffff' },
      },
      spacing: {
        gutter: '24px',
        'navbar-height': '72px',
        'container-margin': '32px',
        'sidebar-width': '280px',
        unit: '8px',
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
