/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherAnalysisRouteImport } from './routes/teacher.analysis'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as ApiReportsTeacherRouteImport } from './routes/api.reports.teacher'
import { Route as ApiReportsStudentRouteImport } from './routes/api.reports.student'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/teacher/notifications',
  path: '/teacher/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAnalysisRoute = TeacherAnalysisRouteImport.update({
  id: '/teacher/analysis',
  path: '/teacher/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsTeacherRoute = ApiReportsTeacherRouteImport.update({
  id: '/api/reports/teacher',
  path: '/api/reports/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsStudentRoute = ApiReportsStudentRouteImport.update({
  id: '/api/reports/student',
  path: '/api/reports/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/timetable': typeof TimetableRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/api/reports/student': typeof ApiReportsStudentRoute
  '/api/reports/teacher': typeof ApiReportsTeacherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/timetable': typeof TimetableRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/api/reports/student': typeof ApiReportsStudentRoute
  '/api/reports/teacher': typeof ApiReportsTeacherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/timetable': typeof TimetableRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/api/reports/student': typeof ApiReportsStudentRoute
  '/api/reports/teacher': typeof ApiReportsTeacherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/login'
    | '/notifications'
    | '/timetable'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/teacher/analysis'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/notifications'
    | '/api/reports/student'
    | '/api/reports/teacher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/login'
    | '/notifications'
    | '/timetable'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/teacher/analysis'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/notifications'
    | '/api/reports/student'
    | '/api/reports/teacher'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/login'
    | '/notifications'
    | '/timetable'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/teacher/analysis'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/notifications'
    | '/api/reports/student'
    | '/api/reports/teacher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  TimetableRoute: typeof TimetableRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  TeacherAnalysisRoute: typeof TeacherAnalysisRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  ApiReportsStudentRoute: typeof ApiReportsStudentRoute
  ApiReportsTeacherRoute: typeof ApiReportsTeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/teacher/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/analysis': {
      id: '/teacher/analysis'
      path: '/teacher/analysis'
      fullPath: '/teacher/analysis'
      preLoaderRoute: typeof TeacherAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/teacher': {
      id: '/api/reports/teacher'
      path: '/api/reports/teacher'
      fullPath: '/api/reports/teacher'
      preLoaderRoute: typeof ApiReportsTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/student': {
      id: '/api/reports/student'
      path: '/api/reports/student'
      fullPath: '/api/reports/student'
      preLoaderRoute: typeof ApiReportsStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  TimetableRoute: TimetableRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  TeacherAnalysisRoute: TeacherAnalysisRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  ApiReportsStudentRoute: ApiReportsStudentRoute,
  ApiReportsTeacherRoute: ApiReportsTeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
